FROM ubuntu:18.04
ARG DEBIAN_FRONTEND=interactive
# ARG DEBIAN_FRONTEND=interactive


RUN apt-get update \
    ffmpeg \
    python3 \
    python3-pip \
    && apt-get clean \
    && apt-get autoremove


RUN mkdir -p /usr/src/app 

WORKDIR /usr/src/app

COPY ./server /usr/src/app
COPY ./requirements.txt /usr/src/app

RUN python3 -m pip install --upgrade pip
RUN pip3 install -r requirements.txt

EXPOSE 8000

CMD [ "python3", "./manage.py", "runserver", "0.0.0.0:8000" ]